#如禁止es的健康检查如下，默认均为开启状态
management:
  health:
    elasticsearch:
      enabled: false

es:
  ip: 192.168.3.91
  port: 9200
  articleType: /search4message/

elasticsearch:
  url: 192.168.10.42
  port: 9200

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:        # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接



thread-pool-factory:
  #IO密集型应用，线程数为2N+1
  corePoolSize: 4
  maxPoolSize: 4
  queueCapacity: 30
  keepAliveSeconds: 120
schedule:
  start_cron_expression:  0 30 23 * * ?
  end_cron_expression: 0 59 7 * * ?
  thread_count: 20
  thread_priority: 5